apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-result-app
  namespace: {{NAMESPACE}}
spec:
  selector:
    matchLabels:
      app: analysis-result-app
  replicas: 1
  template:
    metadata:
      labels:
        app: analysis-result-app
    spec:
      containers:
        - name: analysis-result-container
          image: {{IMAGE_NAME}}
          ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP
            - name: grpc-port
              containerPort: 8082
              protocol: TCP
          env:
            - name: KUMULUZEE_VERSION
              value: {{VERSION}}
            - name: KUMULUZEE_ENV_NAME
              value: {{ENV_NAME}}
            - name: KUMULUZEE_ENV_PROD
              value: "{{ENV_PROD}}"
            - name: KUMULUZEE_SERVER_BASEURL
              value: https://analysis-result{{ENV_SUFFIX}}.mydna.codes
            - name: KUMULUZEE_SERVER_HTTP_PORT
              value: "8080"
            - name: KUMULUZEE_OPENAPIMP_SERVERS
              value: https://analysis-result{{ENV_SUFFIX}}.mydna.codes
            - name: KUMULUZEE_STREAMING_KAFKA_PRODUCER_BOOTSTRAPSERVERS
              value: kafka.kafka:9092
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://analysis-result-db:5432/analysis-result
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              valueFrom:
                secretKeyRef:
                  name: analysis-result-db-credentials
                  key: username
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analysis-result-db-credentials
                  key: password
            - name: KEYCLOAK_AUTHSERVERURL
              valueFrom:
                secretKeyRef:
                  name: keycloak-config
                  key: url
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: keycloak-config
                  key: realm
            - name: KEYCLOAK_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: keycloak-config
                  key: client-id
            - name: KEYCLOAK_AUTH_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-config
                  key: secret
          livenessProbe:
            httpGet:
              path: /health/live
              port: app-port
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: app-port
            initialDelaySeconds: 30
            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-result-service
  namespace: {{NAMESPACE}}
  labels:
    app: analysis-result-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: app-port
      name: rest
    - port: 8082
      targetPort: grpc-port
      protocol: TCP
      name: grpc
  selector:
    app: analysis-result-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: analysis-result
  namespace: {{NAMESPACE}}
spec:
  rules:
    - host: result{{ENV_SUFFIX}}.mydna.codes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: analysis-result-service
                port:
                  number: 8080