kumuluzee:
  name: analysis-result
  version: 1.0.0-SNAPSHOT
  dev:
    scan-libraries:
      - analysis-result-lib
      - rest-lib
  env:
    prod: false
    name: dev
  server:
    show-server-info: false
    base-url: http://localhost:8080
    http:
      port: 8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count, Content-Type"
  grpc:
    server:
      http:
        port: 8082
    clients:
      - name: sequence-bank-grpc-client
        port: 8081
        address: localhost
  streaming:
    kafka:
      producer:
        bootstrap-servers: localhost:9091
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
  graphql:
    mapping: /graphql
    schema:
      base-packages:
        - codes.mydna.lib
  openapi-mp:
    enabled: true
    servers: http://localhost:8080
    ui:
      mapping: /openapi/ui
      enabled: true
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/analysis-result-db
      disk-space-health-check:
        threshold: 100000000
        type: liveness
      kafka-health-check:
        bootstrap-servers: localhost:9091
        minimum-available-nodes: 1
        request-timeout-ms: 1000
  datasources:
    - jndi-name: jdbc/analysis-result-db
      connection-url: jdbc:postgresql://localhost:5432/analysis-result
      username: postgres
      password: postgres
      pool:
        max-size: 20
  migrations:
    enabled: true
    liquibase:
      changelogs:
        - jndi-name: jdbc/analysis-result-db
          file: db/db.changelog-master.xml
          startup:
            drop-all: false
            update: true

keycloak:
  realm: not_set
  auth-server-url: not_set
  client-id: not_set
  auth:
    client-secret: not_set